# -*- coding: utf-8 -*-
"""cleaning_01ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_l23npY2j2MZFTTP0_voSYZAPIROX0n
"""

import kagglehub

path = kagglehub.dataset_download("prevek18/ames-housing-dataset")

print("Path to dataset files:", path)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(path + "/AmesHousing.csv")

"""# Load data"""

def load_data(df):
    df = pd.read_csv(path)
    return df

"""# Check the shape"""

def shape(df):
   return df.shape
shape(df)

"""# Inspect data types"""

def clean_us_info(df):
    print("Shape:", df.shape)

    print("Info before fixing types:")
    df.info()

    df["Neighborhood"] = df["Neighborhood"].astype("string").str.lower().str.strip()

    df["Exterior 1st"] = df["Exterior 1st"].astype("string").str.lower().str.strip()

    print("Info after fixing types:")
    df.info()

    print("Missing values:")
    print(df.isnull().sum().sort_values(ascending=False))
    return df

"""#  Find missing values:

I chose this approach because it handles missing data without removing any rows. For categorical columns like Alley, filling with "None" shows clearly when a feature is absent. For numeric columns like Lot Frontage, using the median avoids distortion from extreme values and keeps the data balanced.
"""

def clean_missing_values(df):

    print("Missing values before cleaning:")
    print(df.isnull().sum().sum())
    df["Alley"] = df["Alley"].fillna("None")
    df["Lot Frontage"] = df["Lot Frontage"].fillna(df["Lot Frontage"].median())
    print("Missing values after cleaning:")
    print(df.isnull().sum().sum())

    return df

"""# Handle duplicates


"""

def clean_duplicateds(df):
    before = df.shape[0]
    df = df.drop_duplicates()
    after = df.shape[0]
    print("Duplicates removed:", before - after)
    return df

"""#  Spot outliers & Handle outliers


"""

def plot_boxplot(df):
    df["SalePrice"].plot.box()
    plt.title("Boxplot of SalePrice")
    plt.show()

plot_boxplot(df)

def outliers(clean, column):
    cap = clean[column].quantile(0.99)
    clean[column] = clean[column].clip(upper=cap)
    return clean

"""# clean_data() function:


"""

def clean_data(path):
    df = load_data(path)
    clean_us_info(df)
    df = clean_missing_values(df)
    df = clean_duplicateds(df)
    df = outliers(df, "Gr Liv Area")
    run_all(df)
    plot_boxplot(df)
    return df

"""# checks"""

assert df["SalePrice"].isnull().sum() == 0, "SalePrice still has missing values"
assert df["Lot Area"].isnull().sum() == 0, "Lot Area still has missing values"

assert (df["SalePrice"] > 0).all(), "Some SalePrice values are <= 0!"
assert df.duplicated().sum() == 0, "There are duplicate rows"

"""# run_all"""

def run_all(clean):
    print("Shape:")
    print(df.shape)

    print("Info:")
    print(clean_us_info(df))

    print("Missing values:")
    print(clean_missing_values(df))

    print("\Duplicates:")
    print(clean_duplicateds(df))

    print("Outliers:")
    print(outliers(df, 'Gr Liv Area'))

run_all(df)

